---

- name: Verify ACI Config
  hosts: all
  connection: local
  collections:
    - cisco.nae
  gather_facts: no
  vars:
    nae_login: &nae_login
        host: https://173.37.213.83/nae/login
        username: admin
        password: soumu101  
    validate_certs: False
  
  tasks:
    - name: Create a pre-change analysis
      cisco.nae.nae_prechange:
        <<: *nae_login
        ag_name: "DMZ-RCDN-Site1"
        name: Jenkins
        state: present
        verify: true
        file: config.json

    - name: Get PCV Result
      cisco.nae.nae_prechange:
        <<: *nae_login
        ag_name: "FAB1"
        name: Jenkins
        state: query
        verify: True
        ignore_sm:
          # We ignore this info event or the pipeline will always fail. 
          - APP_EPG_NOT_DEPLOYED
