---



- name: Add a BD with Subnet to tenant
  hosts: 'dmzapic8'
  collections: 
    - cisco.aci
  gather_facts: no
  connection: local

  #  vars_files:
  #    - apic-vars.yaml 


  tasks:


    - name: Creating BD
      cisco.aci.aci_bd:
        host: "dmzapic8"
        username: "ansible"
        private_key:  "/myJenkinsData/Ansible/APIC/certs/ansible.key"
        certificate_name: "ansible"
        validate_certs: no
        tenant: "sm-Jenkins-Ansible"
        vrf_name: "SMVRF1"
        bd: "newBD8"
        state: present
        use_proxy: no
        output_path: 'config.json'
      delegate_to: localhost


    - name: Create a subnet
      cisco.aci.aci_bd_subnet:
        host: "dmzapic8"
        username: "ansible"
        private_key:  "/myJenkinsData/Ansible/APIC/certs/ansible.key"
        certificate_name: "ansible"
        validate_certs: no
        tenant: "sm-Jenkins-Ansible"
        bd: "newBD8"
        gateway: "10.100.1.1"
        mask: "24"
        state: present
        use_proxy: no
        output_path: 'config.json'
      delegate_to: localhost


